### PR TITLE
Add netbeans project

### PR DESCRIPTION
**Pull request by mingodad**
Add a netbeans project just to show how "old" style cross platform IDE can make life a lot easier.

### CODE REVIEW

**Review by ricomariani — CHANGES_REQUESTED** [review]
I can't take this.  We don't use nb internally and the project would soon go stale or broken.  It also adds another significant dependency to the project.  It also adds a different license to the project.  You're free to distribute this if you like of course but I can't merge it into the main source.

**Comment by mingodad** [comment]
I understand it but I did it to show for any other users that this possibility exists and is still very effective.

**Comment by ricomariani** [comment]
You know we could put a link to the commit in the README.  That finesses the license and still gives people an easy example of where to get the netbeans build.

**Comment by ricomariani** [comment]
I'm gonna close the PR but I encourage you make an edit in the README linking to it.

**Pull request closed without merging**
