### PR TITLE
Replace positional references by named references

### PR DESCRIPTION
**Pull request by mingodad**
, naming can be improved in several places.

With the help of a script to do most of the replacements and with manual fixes after.

I hope this can help on maintenance and further improvements.

Cheers !

### CODE REVIEW

**Comment by ricomariani** [comment]
I think I can take this diff but you can help me by rebasing to head, we had a minor conflict.  There is one other issue but I have to fix that.  There is tooling that scrapes out the grammar from the .y file and it won't handle this kind of thing:

foo[result]:  etc { ... }

The resulting grammar will be wrong.  So I have to make a small change in ys.c (the yacc scraper) to get a clean grammar. This is used to create the grammar.md file for the guide and to make the railroad diagrams.

But otherwise I can take this I think.

I'm also running the tests.  It looks pretty mechanical.  Did you do it all by hand or did a tool help you?  Just curious.

**Comment by ricomariani** [comment]
Well poop.  I don't think I can take this after all.  The bison in our build chain doesn't support the position arguments.  We'll have to upgrade first at the least or everything breaks.

% bison -V   
bison (GNU Bison) 2.3
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

What have you got?

**Comment by ricomariani** [comment]
My devserver has 

linux ~$ bison -V
bison (GNU Bison) 3.0.4
Written by Robert Corbett and Richard Stallman.

So... yeah... I should figure out how to get something more recent into this environment.

**Comment by ricomariani** [comment]
ok on the good news front.  Your PR passes all the tests if I compile it on a devserver.  But I still have to figure out how to get a newer bison in the Mac env and ys.c has to be fixed.

I'll get back to this next week if that's ok :D

I'm kind of excited, my first PR :D

**Comment by ricomariani** [comment]
OK I've got the bison thing sorted.  I do have to fix automatic grammar extraction stuff before I can take this.

**Comment by mingodad** [comment]
> I'm also running the tests. It looks pretty mechanical. Did you do it all by hand or did a tool help you? Just curious.

Look here https://github.com/facebookincubator/CG-SQL/issues/8 for the script I use to help and after it I needed a bit of manual fixes.

**Comment by mingodad** [comment]
I did fixed `ys.c` to skip over `[name_alias]`.

> I think I can take this diff but you can help me by rebasing to head, we had a minor conflict. There is one other issue but I have to fix that. There is tooling that scrapes out the grammar from the .y file and it won't handle this kind of thing:
> 
> foo[result]: etc { ... }
> 
> The resulting grammar will be wrong. So I have to make a small change in ys.c (the yacc scraper) to get a clean grammar. This is used to create the grammar.md file for the guide and to make the railroad diagrams.
>

**Comment by ricomariani** [comment]
I've been working on this PR today and I think I have things pretty much sorted.  I had to make a lot of compensating changes to run on the latest version of bison.  It's all good but there was a lot to sort out.  It's the number of build environments that is the issue.  I'm still working on it :D

**Comment by mingodad** [comment]
This pull request got messy, because whenever I do some changes on my branch that generated this initial pull request they appear here.

- I've did an initial parse implementation to col_attrs for check/collate see here https://github.com/mingodad/CG-SQL/commit/2e3044660ae0dfc8ed6d3043141af0d35802f99c
- I've also added the options to pandoc to generate the table of contents for the guide.html see here https://github.com/mingodad/CG-SQL/commit/9ce44d400a9867daf6015d1b5d087e18fcfbda27
- I've also add the needed compiler options for the src/demo build with gcc see here https://github.com/mingodad/CG-SQL/commit/db6f23daf18ee80ee8d44d58ba7f6a8f1d81362b

**Comment by ricomariani** [comment]
OK I'm set to land the original PR.  It's best not to add more to this one.  You're going to have to merge again anyway.

**Comment by ricomariani** [comment]
You're likely to get some conflicts because it looks like we both did some of the same work to make the diff land.  For instance I included the ys.c changes in my diff also.

**Comment by ricomariani** [comment]
Can you please file a separate PR for the grammar changes though.  I don't want to take them all in the same pull as it is, this merge is already huge on my end due to the bison upgrade.  There's a ton of internal changes you're not seeing to deal with all this. In any case I don't want to do different things in the same PR if possible.  The grammar changes look interesting too. I don't forsee problems accepting them.

**Review by ricomariani — APPROVED** [review]
The .y works fine as is and passes tests.  I had to make assorted infra changes to get a new bison in our environment but that doesn't require anything new in the PR

**Review by ricomariani — APPROVED** [review]
This is fine.

**Review by ricomariani — COMMENTED** [review]
No need to do this I include this when I merged your changes into master.  But this is fine.  We wrote basically the same code fwiw.

**Review by ricomariani — CHANGES_REQUESTED** [review]
These changes are unrelated to the rest of the PR.  I'd like these in their own PR please.  But the changes are fine.

**Review by ricomariani — CHANGES_REQUESTED** [review]
What I did to avoid this problem in other places was I added a rule to the main makefile and then I use the main makefile to build this target. Add a demo target to Makefile instead of this and then we can just do make demo.  That also gets you the sqlite library options for free.

**Review by ricomariani — CHANGES_REQUESTED** [review]
This is nice and clean. I can take it but it in its own PR.  

Is there any semantic analysis we can do on the check?  We might have to defer it until after the table declaration is finished...  But this at least lets you use the syntax with no validation.  

Anyway please put this in its own PR thank you :D

Btw, nice job doing this with basically no internal docs. I imagine you did a lot of reading to get this far.

**Comment by ricomariani** [comment]
While I asked for some of the diffs to come separately they are in fact good diffs  There's only one that really needs any changes and it's pretty easy.  Nice work on this Domingo.  And with zero help...

**Comment by ricomariani** [comment]
The big stuff landed, please rebase to head and give me the additional stuff too.  There are comments in the PR.  Only one commit had any issues and it's the baby commit.

**Review by ricomariani — COMMENTED** [review]
I committed the change to use the Makefile to get the right CFLAGS so you don't have to worry about this one at all.  The other two are good to go I think, just rebase to head and resubmit and I think I can take them directly.

**Pull request closed without merging**
